config/routes.rb
Sample3::Application.routes.draw do
  resources :tasks
  root to: "tasks#index"
end

app/models/single_word_validator.rb
class SingleWordValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors[attribute] << (options[:message] || "should be one word only") unless value =~ /^[a-zA-Z0-9]+$/
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 5, maximum: 200}
  validates :owner, presence: true, length: {maximum: 200}, single_word: true
  validates :tags, length: 0..100
  validates :description, length: {maximum: 500}
  validate :completed_in_present_or_past

  before_validation {|taks| puts "before validation"; true}
  after_validation {|task| puts "after validation"; true}
  before_save {|task| puts "before save"; true}
  after_save :already_saved
  before_create {|task| puts "before create"; true}
  after_create {|task| puts "after create"; true}
  around_create :will_save_in_the_block
  before_update {|task| puts "before update"; true}
  after_update {|task| puts "after update"; true}
  around_update {|task, &block| puts "around update"; block.call}
  before_destroy {|task| puts "before destroy"; true}
  after_destroy {|task| puts "after destroy"; true}
  around_destroy {|task, &block| puts "around destroy"; block.call}

  after_initialize do
    puts "task created!"
  end

  after_find :found_me

  private
  def found_me
    puts "loaded from db: #{id}"
  end

  def completed_in_present_or_past
    errors.add(:completed_at, "You cannot complete a task in the future") if !completed_at.nil? && completed_at >= Time.now
  end

  def already_saved
    puts "after save"
    true
  end

  def will_save_in_the_block
    puts "around create";
    yield
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :json, :js

  # GET /tasks
  # GET /tasks.json
  def index
    @task = Task.new params[:task]
    @tasks = Task.order("title")
    %w{title owner tags description}.each do |field|
      val = @task.send(field.to_sym)
      @tasks = @tasks.where("#{field} like ?", val + "%") if val && val != ""
    end
    respond_with @tasks
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    respond_with @task
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @task.save
    @tasks = Task.all
    respond_with @task
  end

  def update
    @task = Task.find(params[:id])
    @task.completed_at = Time.now
    @task.save
    respond_with @task
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_with @task
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample3</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, remote: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %>
          prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_search_form.html.erb
<%= form_for(@task, method: :get, url: tasks_path, remote: true) do |f| %>
  <td><%= f.text_field :title %></td>
  <td><%= f.text_field :owner %></td>
  <td><%= f.text_field :tags %></td>
  <td><%= f.text_field :description %></td>
  <td><%= f.text_field :completed_at, type: :date %></td>
  <td><%= f.submit "Search" %></td>
  <td></td>
  <td></td>
<% end %>

app/views/tasks/_task.html.erb
<tr id="task<%= task.id %>">
  <td><%= task.title %></td>
  <td><%= task.owner %></td>
  <td><%= task.tags %></td>
  <td><%= task.description %></td>
  <td><%= task.completed_at %></td>
  <td><%= link_to 'Finish', task_path(task), method: :put, remote: true unless task.completed_at %></td>
  <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete, remote: true %></td>
</tr>

app/views/tasks/create.js.erb
<% unless @task.errors.empty? %>
  $(".div_new_task").remove();
  $("<div/>").attr("title", "New Task").attr("class", "div_new_task").append("<%= j render file: "tasks/new.html.erb", layout: false %>").dialog();
<% else %>
  $("tbody").html("<%= j render @tasks %>");
  $(".div_new_task").dialog("close");
  <% @task = Task.new %>
  $("#search_form").html(<% j render partial: "tasks/search_form.html.erb" %>);
<% end %>

app/views/tasks/destroy.js.erb
$("#task<%= @task.id %>").remove();

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Support Tasks</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Owner</th>
      <th>Tags</th>
      <th>Description</th>
      <th>Completed at</th>
      <th></th>
      <th></th>
    </tr>
    <tr id="search_form">
      <%= render partial: 'search_form' %>
    </tr>
  </thead>
  <tbody>
      <%= render @tasks %>
  </tbody>
</table>
<%= link_to 'New Task', new_task_path, remote: true %>

app/views/tasks/index.js.erb
$("tbody").html("<%= j render @tasks %>");

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render 'form' %>

app/views/tasks/new.js.erb
$(".div_new_task").remove();
$("<div/>").attr("title", "New Task").attr("class", "div_new_task").append("<%= j render file: "tasks/new.html.erb", layout: false %>").dialog();

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Owner:</b>
  <%= @task.owner %>
</p>

<p>
  <b>Tags:</b>
  <%= @task.tags %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Completed at:</b>
  <%= @task.completed_at %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$("#task<%= @task.id %>").replaceWith("<%= j render file: "tasks/_task.html.erb", locals: {task: @task} %>");